[package]
name = "vrac"
version = "0.1.0"
authors = ["Grégoire Charvet 黑瓜 <greg+git@geekingfrog.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
warp = "0.2"
tokio = { version = "0.2", features = ["macros", "rt-threaded"] }
http = "0.2.1"
bytes = "0.5"
log = "0.4"
pretty_env_logger = "0.4"
rusqlite = { version = "0.22", features = ["chrono"] }
chrono = "0.4.11"
handlebars = "3.0"
serde = "1.0.106"

# warp
# rusqlite
# handlebars
# serde


# mb read a couple of stuff about serde
